server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: test
    static_configs:
      - labels:
          __path__ : /tmp/json.log
    pipeline_stages:
      - json:
          expressions:
            time: time
            level: level
      - labels:
          level:
      - timestamp:
          source: time
          format: RFC3339Nano